---
title: "SC_ASSIGNMENT_2"


---
## Name : Beno Tiroyakgosi 

# Question 1


```{r}

library(foreach)
set.seed(123)


results <- foreach(i = 1:100, .combine = rbind) %do% {
  
  # generate sample from expdistribution with mean 1
  x <- rexp(1000, rate = 1)
  
  c(mean = mean(x),
    variance = var(x))
}


head(results)

print("Only the top rows of the data frame are printed for illustration purposes. ")
```

# Question 2



```{r}

library(MASS)

set.seed(123)

n = length(galaxies)

vec_median <- numeric(100000)
system.time(
  for (i in 1:100000){
    
    my_sample <- sample(galaxies, n, replace = T)
   
    vec_median[i] <-  median(my_sample)
  }
)

paste0("The bootsrap median estimate under serial processing is ", round(mean(vec_median), 2))


```

```{r}
library(doParallel)


cl <- makeCluster(2)
registerDoParallel(cl)

set.seed(123)

system.time({
  results <- foreach(i = 1:100000, .combine = rbind,
                                 .packages = "MASS") %dopar% {
    sample_data <- sample(galaxies, n, replace = TRUE)
    median(sample_data)
  }
})

paste0("Parallel: 1 iteration per task median is ", round(median(results), 2))

stopCluster(cl)
```

```{r}


cl <- makeCluster(2)
registerDoParallel(cl)

set.seed(123)


# 100000 boot strap samples broken down to 100 mini tasts of 1000 samples

system.time({
  boot_parallel_chunked <- foreach(i = 1:100,
                                   .combine = cbind,
                                   .packages = "MASS") %dopar% {
    
    replicate(1000, {
      sample_data <- sample(galaxies, n, replace = TRUE)
      median(sample_data)
    })
    
  }
})

stopCluster(cl)
```

Parallel computing with 1 iteration is the slowest of the three methods used. When parallel computing is done with a significant amount of work (sampling iterations in this case) being done in each task, it becomes the most efficient method.


# Question 3

```{r}
set.seed(123)

# Parameters
n<- 50
mu_true <- 1
     

cl <- makeCluster(2)
registerDoParallel(cl)

coverage_results <- foreach(i = 1:100,
                            .combine = rbind) %dopar% {
  
  # Sample from exponential distribution
  x <- rexp(n, rate = 1)
  
  boot_means <- numeric(10000)   

for (i in 1:10000) {
  #boot strap samples and statistic
  sample_data <- sample(x, n, replace = TRUE)
  boot_means[i] <- mean(sample_data)
  
}
  
  CI <- quantile(boot_means, probs = c(0.025, 0.975))
  
  # Step 4: Check coverage
  as.numeric(mu_true >= CI[1] & mu_true <= CI[2])
}

stopCluster(cl)

# Estimate coverage
coverage_estimate <- mean(coverage_results)
coverage_estimate
```

#  Question 4

```{r}


library(iterators)

set.seed(1234)


it <- irnorm(5, count = 3)  

# Use foreach to find the max in each vector
max_values <- foreach(v = it, .combine = c) %do% {
  max(v)
}



```


# Question 5





Using replicate

```{r}
set.seed(1234)
system.time({
  it_r <- irnorm(5, count = 3)
  max_values_replicate <- replicate(3, {
    v <- nextElem(it_r)
    max(v)
  })
})


```


Using foreach

```{r}
set.seed(1234)
it_f <- irnorm(5, count = 3)

system.time({
  max_values_foreach <- foreach(v = it_f, .combine = c) %do% {
    max(v)
  }
})

```


Using parLapply
```{r}
cl <- makeCluster(2)

system.time(
  res_par <- parLapply(cl, 1:3, function (i){
    max(rnorm(5))
  })
  
)
```



